{
  "hash": "2350c31d1ac16067eb6cb02a24f07496",
  "result": {
    "engine": "knitr",
    "markdown": "---\ntitle: 'Post-selection Inference in Multiverse Meta-Analysis: The PIMMA Framework'\nshorttitle: PIMMA\nformat:\n  apaquarto-pdf:\n    keep-tex: true\nbibliography: references.bib\nauthor:\n  - name: Matteo Manente\n    affiliations:\n      - name: University of Padova\n        id: 1\n        department: Department of Developmental Psychology and Socialization\n        address: Via Venezia 8\n        city: Padova\n        state: Italy\n        postal-code: 35131\n  - name: Livio Finos\n    affiliations:\n      - name: University of Padova\n        id: 2\n        department: Department of Statistical Sciences\n        address: Via Battisti 241\n        city: Padova\n        state: Italy\n        postal-code: 35121\n    # attributes:\n    #   equal-contributor: true\n  - name: Gianmarco Altoè\n    affiliations:\n      - ref: 1\n  - name: Filippo Gambarota\n    affiliations:\n      - ref: 1\n    corresponding: true\n    email: filippo.gambarota@unipd.it\nabstract: |\n  Meta-analyses, like primary studies, are affected by researcher degrees of freedom: researchers must decide which studies to include, how to compute effect sizes, and which statistical models to use. Different reasonable choices can lead to different results, making multiverse meta-analysis a useful tool for assessing robustness across alternative specifications. However, multiverse meta-analysis also introduces a multiple-testing problem. Current inferential approaches mainly provide a global test, which can establish that at least one specification differs from the null but cannot identify which individual specifications do so while accounting for multiplicity across the full multiverse. We introduce Post-selection Inference in Multiverse Meta-Analysis (PIMMA), which allows inference on individual specifications while controlling the Family-Wise Error Rate (FWER) and accounting for their dependence. In practical terms, PIMMA shows which results remain statistically significant after accounting for multiplicity across all reasonable analytical choices. In simulations, the specification-level test adequately controlled Type I error, with power comparable to robust variance estimation in scenarios where both methods maintained appropriate Type I error control. In an application to meta-analyses of Cognitive Behavioral Therapy efficacy for adult depression, 297 of 336 unique meta-analytic analyses remained significant after step-down max-T adjustment for multiple testing, accounting for dependence among analyses. PIMMA therefore extends multiverse meta-analysis from a global assessment of whether any effect is present to specification-level inference, allowing researchers to evaluate robustness across specifications and identify which individual results remain significant under appropriate error control.\nkeywords: [multiverse analysis, meta-analysis, post-selection inference, multiple testing, sign flipping, family-wise error rate]\nfilters:\n  - _filters/equation-ref.lua\ncrossref:\n  lst-title: \"Code\"\n  lst-prefix: \"Code\"\n---\n\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n# Introduction\n\nResearchers make many decisions throughout a study, including choices about measurement, data preprocessing, and statistical models. When several analytical options are reasonable, researchers can make different defensible choices. These choices are often referred to as *researcher degrees of freedom* [@Simmons2011-ne]. Such flexibility is common in psychology and the social sciences, but also occurs in fields such as medicine and biology [@Errington2021-fb; @Nosek2022-ab]. Because different analytical choices can lead to different conclusions even when applied to the same data and research question [@Silberzahn2018-yu], researchers may face a multiverse of reasonable analytical specifications [@Steegen2016-gx].\n\nBecause researcher degrees of freedom are a natural and often unavoidable part of the research process, what matters is making their impact on the results transparent. *Multiverse analysis* addresses this by examining all reasonable combinations of analytical choices and showing how the results vary across specifications [@Steegen2016-gx; @Simonsohn2020-sr]. This makes the variability introduced by analytical decisions explicit and allows researchers to assess the robustness of their conclusions.\n\nResearcher degrees of freedom are not inherently problematic when analytical choices are determined independently of the observed results. However, when multiple reasonable specifications are examined and the results influence which analyses are emphasized or interpreted, a multiple-testing and post-selection inference problem arises [@Gelman2013-hm]. Without appropriate adjustment, this can increase the risk that false positive findings are reported as evidence of an effect [@Wicherts2016-cz].\n\nThese issues are not limited to primary studies. Meta-analyses involve many of the same researcher degrees of freedom. Meta-analysts must decide, for example, which studies to include, how to compute effect sizes and their sampling variances, and which meta-analytic model and estimator to use. Additional choices arise with complex data structures requiring aggregation, imputation, or multilevel and multivariate modeling [@Van-den-Noortgate2013-lu; @Cheung2013-hw]. Different defensible choices can therefore lead to different meta-analytic conclusions. This makes meta-analysis particularly well suited to a multiverse approach, which allows researchers to examine how conclusions change across reasonable analytical choices within the same evidence base.\n\nAssessing robustness to these choices is particularly important in meta-analysis because systematic reviews and meta-analyses can strongly influence scientific, clinical, and policy conclusions [@Higgins2019-ck; @Murad2016-yw]. Accordingly, multiverse meta-analysis has recently been used to examine topics including psychotherapy and digital interventions for depression [@Plessen2023-ex; @Plessen2025-ip], IQ and mental illness [@Fries2025-aq], oxytocin administration [@Kang2025-se], and the effects of music listening on epilepsy [@Oberleiter2023-zz].\n\nMost approaches to multiverse analysis remain primarily descriptive. For example, the original multiverse analysis [@Steegen2016-gx] and the *Vibration of Effects* framework [@Patel2015-pn] show how estimates and $p$-values vary across specifications, but do not provide formal inference that accounts for testing many specifications within the same multiverse. From an inferential perspective, examining many specifications creates a multiple-testing problem. Because specifications are often based on the same data, their tests are also generally dependent, and interpreting their unadjusted $p$-values can lead to misleading conclusions [@Girardi2024-ip; @Westfall1992-es; @Goeman2014-om].\n\nInference in a multiverse can focus either on the whole set of specifications or on individual specifications. A global test asks whether there is evidence that at least one specification differs from the null. This can be useful, but it does not tell us which individual specifications remain statistically significant after the full multiverse has been examined. A global rejection alone is often of limited scientific interest [@Oberauer2019-xv, p. 1609], because researchers are typically more interested in which analytical conclusions remain supported across specifications.\n\nExisting inferential approaches to multiverse analysis have focused mainly on global testing. Resampling-based multiverse methods test the collection of analyses as a whole [@Simonsohn2020-sr]. In meta-analysis, @Voracek2019 extended multiverse-analysis approaches to distinguish between choices about which evidence to include and how to analyze it. This framework has subsequently been applied in several multiverse meta-analyses [e.g., @Pietschnig2022-mg; @Plessen2023-ex], with the database assembled by @Plessen2023-ex providing the basis for the empirical application presented below. However, these approaches do not provide general multiplicity-adjusted inference for the individual specifications in the multiverse.\n\nThe more recent *Post-selection Inference in Multiverse Analysis* (PIMA) framework [@Girardi2024-ip] addresses this limitation using sign-flipping score tests and joint resampling across specifications. PIMA provides both a global test and adjusted inference for individual specifications while controlling the Family-Wise Error Rate (FWER). PIMA is also applicable to a wider range of outcome types and statistical models than SCA.\n\nExtending PIMA to meta-analysis requires addressing two problems at the same time. First, inference within a single meta-analysis can already be unreliable when the number of studies is small or heterogeneity is considerable [@Follmann1999-ha; @Viechtbauer2015-tn]. Second, examining many specifications creates an additional multiple-testing problem across the multiverse. Solving only one of these problems is not enough: controlling Type I error within each meta-analysis does not address multiple testing across the multiverse, while adjusting for multiple testing cannot correct unreliable inference within individual meta-analyses.\n\nResampling-based inference has been proposed for several meta-analytic settings, including average effects, moderator tests, and multivariate meta-analysis [@Follmann1999-ha; @Higgins2004-gf; @Viechtbauer2015-tn; @Noma2020-fi]. However, these methods were developed for inference within a single meta-analytic model and do not directly provide joint inference across many overlapping specifications.\n\nScore-based sign flipping provides a natural way to connect these two levels of inference. Rather than repeatedly refitting models after permuting the data, the method resamples study-level score contributions. The same study-level transformations can then be applied across overlapping specifications, preserving their dependence and allowing joint inference across the multiverse [@Hemerik2020-nq; @De-Santis2025-ga; @De-Santis2025-ej].\n\nIn this paper, we introduce Post-Selection Inference in Multiverse Meta-Analysis (PIMMA), which extends the PIMA framework to mixed-effects meta-analysis and meta-regression. We first develop a study-level sign-flipping test for individual meta-analytic specifications. We then show how the same sign-flipping transformations can be used across the whole multiverse to obtain both a global test and adjusted inference for individual specifications. Finally, we evaluate the specification-level test in simulations and illustrate the full PIMMA workflow in a multiverse meta-analysis of Cognitive Behavioral Therapy (CBT) for depression based on the data of @Plessen2023-ex.\n\n# Mixed-Effects Meta-Regression\n\nIn this section, we present the standard independent-study formulation of the mixed-effects meta-regression model, following @Viechtbauer2015-tn. In a meta-analysis with $k$ independent studies, let $y_i$ and $v_i$ denote respectively the observed effect size estimate and the sampling variance for the $i$-th study. The model can be written as\n\n$$\n\\begin{aligned}\n\\mathbf{y} &= \\mathbf{D} \\boldsymbol{\\beta} + \\mathbf{u} + \\mathbf{e}, \\\\\n\\mathbf{u} &\\sim \\mathcal{N}(\\mathbf{0}, \\tau^2\\mathbf{I}), \\\\\n\\mathbf{e} &\\sim \\mathcal{N}(\\mathbf{0}, \\mathbf{V}),\n\\end{aligned}\n$${#eq-meta-reg}\n\nwhere $\\mathbf{y}$ is the $k \\times 1$ vector of observed effect size estimates, $\\mathbf{D}$ is the $k \\times p$ model matrix (including the intercept), and $\\boldsymbol{\\beta}$ is the vector of $p$ regression coefficients. The vector $\\mathbf{u}$ contains the study-level random effects and is assumed to follow a normal distribution with mean zero and variance $\\tau^2$, whereas $\\mathbf{e}$ contains the within-study sampling errors. The sampling errors are assumed to be normally distributed with a diagonal variance-covariance matrix $\\mathbf{V} = \\operatorname{diag}(v_1,\\ldots,v_k)$, where the sampling variances $v_i$ are treated as known. It follows that the marginal distribution of the observed effect size estimates is\n\n$$\n\\mathbf{y} \\sim \\mathcal{N}\\left(\\mathbf{D}\\boldsymbol{\\beta}, \\boldsymbol{\\Sigma}\\right),\n\\qquad\n\\boldsymbol{\\Sigma} = \\mathbf{V} + \\tau^2 \\mathbf{I}.\n$${#eq-marginal}\n\nThe model in @eq-marginal is used as a working model for estimation and score construction. As detailed below, the standardized sign-flipping procedure remains asymptotically valid under misspecification of the conditional variance structure, subject to the stated regularity conditions.\n\nFor a fixed value of $\\tau^2$, the regression coefficients can be estimated by weighted least squares. Let $\\mathbf{W} = \\boldsymbol{\\Sigma}^{-1} = (\\mathbf{V} + \\tau^2 \\mathbf{I})^{-1}$. The estimator of $\\boldsymbol{\\beta}$ is then\n\n$$\n\\mathbf{b}\n=\n(\\mathbf{D}^{\\top}\\mathbf{W}\\mathbf{D})^{-1}\n\\mathbf{D}^{\\top}\\mathbf{W}\\mathbf{y}.\n$${#eq-wls}\n\nSince $\\tau^2$ is unknown, the weights used in practice are obtained by replacing $\\tau^2$ with an estimate $\\hat{\\tau}^2$, so that $\\hat{\\mathbf{W}} = (\\mathbf{V}+\\hat{\\tau}^2\\mathbf{I})^{-1}$. Several estimators have been proposed for $\\tau^2$ [see @Viechtbauer2005-yh]. We focus here on the DerSimonian--Laird estimator [-@DerSimonian1986-ju], as a commonly used non-iterative method-of-moments estimator, and on the restricted maximum likelihood (REML) method.\n\nBoth estimators can be expressed using the weight-dependent matrix\n\n$$\n\\mathbf{P}(\\tau^2)\n=\n\\mathbf{W}\n-\n\\mathbf{W}\\mathbf{D}\n(\\mathbf{D}^{\\top}\\mathbf{W}\\mathbf{D})^{-1}\n\\mathbf{D}^{\\top}\\mathbf{W}.\n$${#eq-het-p}\n\nFor the DerSimonian--Laird estimator, $\\mathbf{W}$ is computed using only the inverse sampling variances, that is, $w_i = v_i^{-1}$, and the corresponding matrix is therefore $\\mathbf{P}(0)$. Since $p$ denotes the total number of regression coefficients, including the intercept, the estimator is given by\n\n$$\n\\hat{\\tau}^2_{\\mathrm{DL}}\n=\n\\frac{\n\\mathbf{y}^{\\top}\\mathbf{P}(0)\\mathbf{y} - (k-p)\n}{\n\\operatorname{tr}\\{\\mathbf{P}(0)\\}\n},\n$${#eq-het-dl}\n\nwhere negative $\\hat{\\tau}^2_{\\mathrm{DL}}$ values are truncated to zero.\n\nLikelihood-based estimators are obtained from the marginal normal model in [-@eq-marginal]. The log-likelihood of the random-effects model can be written as\n\n$$\n\\ell_{\\mathrm{ML}}(\\boldsymbol{\\beta}, \\tau^2)\n=\n-\\frac{1}{2}\n\\left[\nk\\log(2\\pi)\n+\n\\log|\\boldsymbol{\\Sigma}|\n+\n(\\mathbf{y}-\\mathbf{D}\\boldsymbol{\\beta})^{\\top}\n\\boldsymbol{\\Sigma}^{-1}\n(\\mathbf{y}-\\mathbf{D}\\boldsymbol{\\beta})\n\\right].\n$${#eq-ml-loglik}\n\nFor a fixed value of $\\tau^2$, maximizing @eq-ml-loglik with respect to $\\boldsymbol{\\beta}$ gives the weighted least squares estimator in @eq-wls. Substituting this estimator into the likelihood yields the profiled log-likelihood\n\n$$\n\\ell_{\\mathrm{ML}}^{p}(\\tau^2)\n=\n-\\frac{1}{2}\n\\left[\nk\\log(2\\pi)\n+\n\\log|\\boldsymbol{\\Sigma}|\n+\n\\mathbf{y}^{\\top}\\mathbf{P}(\\tau^2)\\mathbf{y}\n\\right].\n$${#eq-ml-profile}\n\nHowever, maximum likelihood estimators of variance components are generally downward biased because they do not account for the loss of degrees of freedom associated with estimating the fixed effects. Restricted maximum likelihood addresses this issue by maximizing a likelihood based on linear combinations of the data that remove the fixed effects. Up to an additive constant independent of $\\tau^2$, the restricted log-likelihood can be written as\n\n$$\n\\ell_{\\mathrm{REML}}(\\tau^2)\n=\n-\\frac{1}{2}\n\\left[\n\\log|\\boldsymbol{\\Sigma}|\n+\n\\log|\\mathbf{D}^{\\top}\\mathbf{W}\\mathbf{D}|\n+\n\\mathbf{y}^{\\top}\\mathbf{P}(\\tau^2)\\mathbf{y}\n\\right]\n+ c,\n$${#eq-reml-loglik}\n\nwhere $c$ is independent of $\\tau^2$.\n\nAfter $\\hat{\\tau}^2_{\\mathrm{REML}}$ has been obtained, the final estimates of the meta-regression coefficients are computed using $\\hat{\\tau}^2_{\\mathrm{REML}}$ in @eq-wls.\n\nSeveral methods have been proposed to perform statistical inference on the regression coefficients in mixed-effects meta-regression models [see @Viechtbauer2015-tn]. Here, we consider the Wald test, the Knapp--Hartung test (KH) [@Knapp2003-qx], the modified Knapp--Hartung test (mKH) [@Viechtbauer2015-tn], Robust Variance Estimation (RVE) with CR2 adjustment and Satterthwaite degrees of freedom [@White1980-tl; @Tipton2015-bo; @Pustejovsky2018-am], and permutation testing [@Follmann1999-ha; @Higgins2004-gf].\n\nUnder Wald, the variance-covariance matrix of the estimated regression coefficients is estimated as\n\n$$\n\\hat{\\mathbf{V}}_{\\mathbf{b}}\n=\n(\\mathbf{D}^{\\top}\\hat{\\mathbf{W}}\\mathbf{D})^{-1},\n$${#eq-vb-wald}\n\nwhere\n\n$$\n\\hat{\\mathbf{W}}\n=\n(\\mathbf{V}+\\hat{\\tau}^2\\mathbf{I})^{-1}.\n$$\n\nThe standard error of $b_j$ is given by the square root of the corresponding diagonal element of $\\hat{\\mathbf{V}}_{\\mathbf{b}}$. The Wald-type test statistic is then defined as\n\n$$\nz_j\n=\n\\frac{b_j}{\\sqrt{\\widehat{\\operatorname{Var}}(b_j)}}.\n$${#eq-wald-stat}\n\nUnder the null hypothesis $H_0:\\beta_j = 0$, $z_j$ is compared against the critical value calculated at the $\\alpha$ level of a standard normal distribution.\n\nKH uses the same coefficient estimates but replaces the standard variance-covariance matrix @eq-vb-wald with an adjusted version as $\\hat{\\mathbf{V}}_{\\mathbf{b},\\mathrm{KH}} = s^2 \\hat{\\mathbf{V}}_{\\mathbf{b}}$ with $s^2$ calculated as\n\n$$\ns^2\n=\n\\frac{\n\\mathbf{y}^{\\top}\\hat{\\mathbf{P}}\\mathbf{y}\n}{\nk-p\n}.\n$${#eq-kh-scale}\n\nwhere $\\hat{\\mathbf{P}}=\\mathbf{P}(\\hat{\\tau}^2)$ uses the fitted random-effects weights.\n\nThe test statistic is computed as in @eq-wald-stat, using the corresponding adjusted standard error, and is compared against a $t$ distribution with $k-p$ degrees of freedom. The mKH test sets $s^2 = 1$ whenever $s^2 < 1$, thereby preventing the adjusted standard error from being smaller than the standard Wald standard error.\n\nWe additionally considered RVE. Although robust variance estimation is often used to accommodate dependent effect sizes within studies [@Hedges2010-ik], in the present setting each study contributes one independent effect size and is therefore treated as a singleton cluster. Let $\\mathbf{d}_i^{\\top}$ denote row $i$ of the design matrix, $\\mathbf{A}=(\\mathbf{D}^{\\top}\\hat{\\mathbf{W}}\\mathbf{D})^{-1}$, and $\\hat e_i=y_i-\\mathbf{d}_i^{\\top}\\mathbf{b}$.\n\n$$\n\\widehat{\\mathbf{V}}_{\\mathbf{b},\\mathrm{CR0}}\n=\n\\mathbf{A}\n\\left(\n\\sum_{i=1}^{k}\n\\hat w_i^2\n\\mathbf{d}_i\\mathbf{d}_i^{\\top}\n\\hat e_i^2\n\\right)\n\\mathbf{A}.\n$$\n\nThis estimator permits arbitrary heteroskedasticity across independent studies and does not require the true conditional variance to equal $v_i+\\hat\\tau^2$ [@White1980-tl]. To reduce finite-sample bias, we used the CR2 bias-reduced linearization adjustment for the sandwich variance estimator [@Tipton2015-bo; @Pustejovsky2018-am]. For singleton clusters with inverse-variance weights, CR2 rescales each residual by $(1-h_i)^{-1/2}$, where $h_i=\\hat w_i\\mathbf{d}_i^{\\top}\\mathbf{A}\\mathbf{d}_i$ is its weighted leverage. For testing $H_0:\\beta_j=0$, the resulting CR2-adjusted test statistic\n\n$$\nt_{j,\\mathrm{CR2}}\n=\n\\frac{b_j}\n{\\sqrt{[\\widehat{\\mathbf{V}}_{\\mathbf{b},\\mathrm{CR2}}]_{jj}}}\n$$\n\nwas compared with a $t$ distribution using coefficient-specific Satterthwaite degrees of freedom. These degrees of freedom reflect the effective amount of independent information for the tested moderator and can be substantially smaller than $k-p$ when leverage or study weights are highly uneven [@Tipton2015-bo]. RVE is robust to misspecification of the variance structure but not to misspecification of the conditional mean or violations of independence between studies. It was implemented by treating study identifiers as singleton clusters using the `clubSandwich` package [@Pustejovsky2026-sk] through the `metafor::robust()` function [@Viechtbauer2010-xz].\n\nPermutation testing provides a resampling-based alternative for testing moderator effects. Following the implementation in `metafor::permutest()` and the permutation approach discussed by @Viechtbauer2015-tn, this procedure is formulated for inference within a single meta-regression model. Because the resampling unit is the model matrix of that specific model, it does not provide a common study-level transformation that can be applied across multiple, potentially overlapping specifications, and therefore does not directly yield the joint resampling distribution required for multiverse inference. For models with moderators, the rows of the complete model matrix $\\mathbf{D}$ are permuted while the observed effect-size estimates and sampling variances are kept fixed. For each permutation, the complete mixed-effects meta-regression model is refitted, including re-estimation of the regression coefficients and $\\tau^2$. For a given coefficient $b_j$, let $z_j^{(1)}$ denote the Wald-type statistic obtained from the original data and let $z_j^{(r)}$, $r=2,\\ldots,B$, denote the statistics obtained from $B-1$ random permutations. The original data configuration is included as the first configuration. For a two-sided test, the permutation $p-value$ is computed as\n\n$$\np_{\\mathrm{perm}}\n=\n\\frac{\n\\sum_{r=1}^{B}\n\\mathbb{I}\\left(\n|z_j^{(r)}| \\geq |z_j^{(1)}|\n\\right)\n}{\nB\n}.\n$${#eq-perm-p}\n\nWhen all unique permutations of the model matrix are enumerated, this gives the exact permutation distribution. Otherwise, the distribution is approximated using a finite number of random permutations.\n\n\n# Score-Based Sign-Flipping Inference for Meta-Regression\n\nTesting a coefficient in the mixed-effects meta-regression model can be based on its score evaluated under the null hypothesis. The score statistic itself does not determine how its reference distribution is obtained; here, we construct that distribution by sign-flipping the study-level effective score contributions, thereby connecting meta-regression inference to the PIMA framework. In contrast to the permutation procedure described above, resampling is applied to the score contributions rather than to the rows of the model matrix.\n\nWe focus on a single focal regression coefficient. We partition the complete design matrix as $\\mathbf{D}=[\\mathbf{X},\\mathbf{Z}]$, where $\\mathbf{X}$ is the $k \\times 1$ design vector for the focal predictor and $\\mathbf{Z}$ contains the nuisance predictors, including the intercept when appropriate. The corresponding model can be written as\n\n$$\n\\mathbf{y}\n\\sim\n\\mathcal{N}\n\\left(\n\\mathbf{X}\\beta\n+\n\\mathbf{Z}\\boldsymbol{\\gamma},\n\\boldsymbol{\\Sigma}\n\\right),\n\\qquad\n\\boldsymbol{\\Sigma}\n=\n\\mathbf{V}\n+\n\\tau^2\\mathbf{I}.\n$${#eq-flipmeta-model}\n\nWe test $H_0:\\beta=\\beta_{\\mathrm{null}}$, usually with $\\beta_{\\mathrm{null}}=0$, while $\\boldsymbol{\\gamma}$ and $\\tau^2$ remain nuisance parameters. Under the null model, we estimate $\\hat{\\boldsymbol{\\gamma}}_{H_0}$ and $\\hat{\\tau}_{H_0}^2$ and define\n\n$$\n\\widehat{\\boldsymbol{\\Sigma}}_{H_0}\n=\n\\mathbf{V}\n+\n\\hat{\\tau}_{H_0}^2\\mathbf{I},\n\\qquad\n\\widehat{\\mathbf{W}}_{H_0}\n=\n\\widehat{\\boldsymbol{\\Sigma}}_{H_0}^{-1}.\n$${#eq-null-weights}\n\nThe fitted values and residuals under the null are\n\n$$\n\\hat{\\boldsymbol{\\mu}}_{H_0}\n=\n\\mathbf{X}\\beta_{\\mathrm{null}}\n+\n\\mathbf{Z}\\hat{\\boldsymbol{\\gamma}}_{H_0},\n\\qquad\n\\hat{\\mathbf{r}}_{H_0}\n=\n\\mathbf{y}\n-\n\\hat{\\boldsymbol{\\mu}}_{H_0}.\n$${#eq-null-residuals}\n\nAlthough $\\tau^2$ is a nuisance parameter, it does not require an additional projection in the effective score. In the Gaussian meta-regression model, the parameters of the mean and the variance parameter $\\tau^2$ are Fisher-orthogonal,\n\n$$\n\\mathcal{I}_{\\beta,\\tau^2}=0,\n\\qquad\n\\mathcal{I}_{\\boldsymbol{\\gamma},\\tau^2}=\\mathbf{0}.\n$$\n\nThis follows because the score for the mean parameters is linear in the residuals, whereas the score for $\\tau^2$ is quadratic in the residuals, and the corresponding cross-information is zero under the Gaussian model. Therefore, nuisance adjustment in the effective score is required for $\\boldsymbol{\\gamma}$, while $\\tau^2$ enters the test through the null working weights $\\widehat{\\mathbf{W}}_{H_0}$.\n\nThe connection with the general sign-flipping score framework follows directly from the Gaussian identity-link form of the meta-regression model. In the general framework, let $\\mathbf{V}_Y=\\operatorname{Var}(\\mathbf{y})$ denote the response variance matrix, to distinguish it from the within-study sampling-variance matrix $\\mathbf{V}$ used in meta-analysis. The working weight matrix is\n\n$$\n\\mathbf{W}\n=\n\\mathbf{D}_{\\mu}\n\\mathbf{V}_Y^{-1}\n\\mathbf{D}_{\\mu},\n$$\n\nwhere $\\mathbf{D}_{\\mu}=\\operatorname{diag}(\\partial\\mu_i/\\partial\\eta_i)$. For the Gaussian identity-link meta-regression model, $\\mathbf{D}_{\\mu}=\\mathbf{I}$ and\n\n$$\n\\mathbf{V}_Y\n=\n\\boldsymbol{\\Sigma}\n=\n\\mathbf{V}+\\tau^2\\mathbf{I}.\n$$\n\nTherefore,\n\n$$\n\\mathbf{W}\n=\n\\boldsymbol{\\Sigma}^{-1},\n\\qquad\n\\mathbf{V}_Y^{-1/2}\n=\n\\mathbf{W}^{1/2}.\n$$\n\nThe general effective score of @Hemerik2020-nq and @De-Santis2025-ga therefore reduces directly to the following score for mixed-effects meta-regression. Define the weighted hat matrix for the nuisance design as\n\n$$\n\\mathbf{H}_Z\n=\n\\widehat{\\mathbf{W}}_{H_0}^{1/2}\n\\mathbf{Z}\n\\left(\n\\mathbf{Z}^{\\top}\n\\widehat{\\mathbf{W}}_{H_0}\n\\mathbf{Z}\n\\right)^{-1}\n\\mathbf{Z}^{\\top}\n\\widehat{\\mathbf{W}}_{H_0}^{1/2}.\n$${#eq-hz}\n\nWhen there are no nuisance predictors, $\\mathbf{Z}$ has zero columns and we define $\\mathbf{H}_Z=\\mathbf{0}$, so that $\\mathbf{I}-\\mathbf{H}_Z=\\mathbf{I}$. The effective score, evaluated under $H_0$, is then\n\n$$\nS_{\\mathrm{eff}}\n=\nk^{-1/2}\n\\mathbf{X}^{\\top}\n\\widehat{\\mathbf{W}}_{H_0}^{1/2}\n(\\mathbf{I}-\\mathbf{H}_Z)\n\\widehat{\\mathbf{W}}_{H_0}^{1/2}\n\\hat{\\mathbf{r}}_{H_0}.\n$${#eq-effective-score-observed}\n\nThis is the direct specialization of the general flipscores effective score to the marginal Gaussian meta-regression model. Equivalently, it can be written as a sum of study-level effective score contributions,\n\n$$\nS_{\\mathrm{eff}}\n=\nk^{-1/2}\n\\sum_{i=1}^{k}\n\\nu_i,\n$${#eq-score-contributions-observed}\n\nwhere $\\nu_i$ is the contribution of study $i$ to the effective score. Define the focal predictor residualized with respect to the nuisance predictors as\n\n$$\n\\widetilde{\\mathbf{X}}\n=\n\\mathbf{X}\n-\n\\mathbf{Z}\n\\left(\n\\mathbf{Z}^{\\top}\n\\widehat{\\mathbf{W}}_{H_0}\n\\mathbf{Z}\n\\right)^{-1}\n\\mathbf{Z}^{\\top}\n\\widehat{\\mathbf{W}}_{H_0}\n\\mathbf{X}.\n$$\n\nIf there are no nuisance predictors, this residualization is the identity and $\\widetilde{\\mathbf{X}}=\\mathbf{X}$. The contribution of study $i$ can then be written as\n\n$$\n\\nu_i\n=\n\\tilde{x}_i\n\\hat{w}_{H_0,i}\n\\hat{r}_{H_0,i}.\n$${#eq-score-contribution-general}\n\nWith a single focal moderator and an intercept-only nuisance model, this reduces to\n\n$$\n\\nu_i\n=\n(x_i-\\bar{x}_w)\n\\hat{w}_{H_0,i}\n\\hat{r}_{H_0,i},\n\\qquad\n\\bar{x}_w\n=\n\\frac{\\sum_{i=1}^{k}\\hat{w}_{H_0,i}x_i}{\\sum_{i=1}^{k}\\hat{w}_{H_0,i}}.\n$${#eq-simple-contribution}\n\nThus, in this case, the effective score is a weighted association between the centered moderator and the residuals under the null model. Under $H_0$, the ideal effective score contributions based on the true nuisance quantities have mean zero. Replacing the nuisance quantities by their estimates under the null yields the asymptotically equivalent score used in practice [@Hemerik2020-nq; @De-Santis2025-ga].\n\nLet $\\mathbf{F}^{(r)}=\\operatorname{diag}(g_1^{(r)},\\ldots,g_k^{(r)})$ be a diagonal sign-flipping matrix, with $g_i^{(r)}\\in\\{-1,+1\\}$ and $r=1,\\ldots,B$. The first flip is fixed as the identity, $\\mathbf{F}^{(1)}=\\mathbf{I}$, and the remaining $B-1$ matrices are sampled at random. Each sign-flipped score is standardized using the leading term of its flip-specific conditional variance [@De-Santis2025-ga; @Girardi2024-ip]. In the present meta-regression setting, this term is estimated as\n\n$$\n\\widehat{C}^{(r)}\n=\nk^{-1}\n\\mathbf{X}^{\\top}\n\\widehat{\\mathbf{W}}_{H_0}^{1/2}\n(\\mathbf{I}-\\mathbf{H}_Z)\n\\mathbf{F}^{(r)}\n(\\mathbf{I}-\\mathbf{H}_Z)\n\\mathbf{F}^{(r)}\n(\\mathbf{I}-\\mathbf{H}_Z)\n\\widehat{\\mathbf{W}}_{H_0}^{1/2}\n\\mathbf{X}.\n$${#eq-flip-variance}\n\nThe resulting signed standardized statistic is\n\n$$\nU^{(r)}\n=\n\\frac{\nk^{-1/2}\n\\sum_{i=1}^{k}\ng_i^{(r)}\n\\nu_i\n}{\n\\sqrt{\\widehat{C}^{(r)}}\n}.\n$${#eq-univ-score-stat}\n\nFor a two-sided test, the statistic used for rejection is\n\n$$\nT^{(r)}=\\left|U^{(r)}\\right|.\n$$\n\nThe sign-flipping $p-value$ for a single specification is\n\n$$\np_{\\mathrm{flip}}\n=\n\\frac{\n\\sum_{r=1}^{B}\n\\mathbb{I}\n\\left(\nT^{(r)}\n\\geq\nT^{(1)}\n\\right)\n}{B}.\n$${#eq-flip-p}\n\nThe asymptotic validity of this meta-regression specialization is inherited from the general standardized sign-flipping score framework under the corresponding regularity conditions. As customary in conventional mixed-effects meta-analysis, the within-study sampling variances $v_i$ are treated as known. We further assume that the meta-regression mean model is correctly specified, that the complete design matrix has full rank and fixed dimension as $k$ increases, that the estimated working weights converge to finite and non-degenerate limits, and that the score contributions satisfy the regularity and Lindeberg conditions of @De-Santis2025-ga, excluding asymptotically dominating studies.\n\nIn particular, for the heterogeneity estimator used under the null, assume that\n\n$$\n\\hat{\\tau}_{H_0}^2\n\\xrightarrow{P}\n\\widetilde{\\tau}^2\n$$\n\nfor some finite $\\widetilde{\\tau}^2\\geq0$. For each study, continuity then gives\n\n$$\n\\hat{w}_{H_0,i}\n=\n\\frac{1}{v_i+\\hat{\\tau}_{H_0}^2}\n\\xrightarrow{P}\n\\frac{1}{v_i+\\widetilde{\\tau}^2}\n=\n\\widetilde{w}_i.\n$$\n\nThus, estimation of $\\tau^2$ produces a convergent working-weight sequence of the type allowed by the general sign-flipping framework, provided the remaining regularity conditions hold. Importantly, $\\widetilde{\\tau}^2$ need not correspond to the true variance structure. Under variance misspecification, $\\widehat{C}^{(r)}$ is a working-model variance factor and need not consistently estimate the true conditional variance of the score. The asymptotic validity of the standardized study-level sign-flipping test for $H_0:\\beta=\\beta_{\\mathrm{null}}$ follows instead from the sign-flipping argument under the stated regularity conditions [@De-Santis2025-ga]. This robustness does not extend to misspecification of the mean model or to violations of the assumed independence structure.\n\nFor each tested null hypothesis, the constrained null meta-regression model is fitted once, and the resulting nuisance-parameter estimates are held fixed across sign flips. The reference distribution is then constructed by applying the $B$ sign-flipping transformations directly to the study-level effective score contributions without re-estimating the regression coefficients or $\\tau^2$. This differs from `metafor::permutest()`, where the complete meta-regression model, including $\\tau^2$, is refitted for every permutation [@Higgins2004-gf]. More importantly for the present purpose, the study-level score representation makes it possible to apply common sign-flipping transformations across overlapping meta-analytic specifications, thereby preserving their dependence under resampling and enabling joint inference across specifications.\n\n\n\nWe explored this computational difference in the supplementary materials ([github.com/filippogambarota/pimma](https://github.com/filippogambarota/pimma)). For a meta-analysis with $k = 100$ studies and 3 predictors, using 1000 resampling transformations for each procedure, `metafor::permutest()` takes roughly 10 seconds, compared with 0.1 seconds for the score sign-flipping approach. The score sign-flipping test is implemented in the `flipmeta` R package (<https://github.com/filippogambarota/flipmeta>). Hereafter, we refer to this extension of the flipscores framework to meta-analysis as `flipmeta`.\n\n# From `flipmeta` to PIMMA\n\nThe score sign-flipping test provides inference for a single meta-analytic specification. PIMA extends this logic to a multiverse by applying the same sign-flipping transformations across all admissible specifications and combining the resulting standardized score statistics across specifications [@Girardi2024-ip]. We consider a fixed finite set of $S$ admissible meta-analytic specifications, defined independently of the observed specification-level results and indexed by $s=1,\\ldots,S$, while the asymptotic results refer to an increasing number of independent studies. Post-selection inference concerns selection among this fixed family after the results have been inspected, rather than data-dependent construction of the family itself.\n\nSpecifications may differ in inclusion criteria, effect-size metric, moderator coding, heterogeneity estimator, or other analytical choices, provided that each specification can be represented within the independent mixed-effects meta-regression framework described above and tests a compatible focal null hypothesis. Compatibility requires that $\\beta_s = 0$ represent the same absence of an effect across specifications, even when the effect is expressed using different metrics or model formulations. Let $\\beta_s$ denote the focal coefficient in specification $s$ and define\n\n$$\nH_s:\\beta_s=0.\n$$\n\nThe global null hypothesis is the intersection of the specification-specific null hypotheses,\n\n$$\nH_{\\mathrm{global}}\n=\n\\bigcap_{s=1}^{S} H_s\n=\n\\left\\{\n\\beta_s=0\n\\text{ for all }\ns=1,\\ldots,S\n\\right\\}.\n$${#eq-global-null}\n\nRejecting this hypothesis implies that the focal effect is non-null in at least one specification, but does not identify which specification is responsible for the rejection [@Girardi2024-ip].\n\nTo define common resampling transformations across specifications, let $\\mathcal{I} = \\{1,\\ldots,K\\}$ denote the master set of independent studies occurring in the multiverse, and let $\\mathcal{I}_s\\subseteq\\mathcal{I}$ denote the subset of studies included in specification $s$. For each transformation $r=1,\\ldots,B$, a single sign $g_i^{(r)}\\in\\{-1,+1\\}$ is generated for each study $i\\in\\mathcal{I}$, with $g_i^{(1)}=1$ for all $i$. The sign-flipping matrix used in specification $s$ is then\n\n$$\n\\mathbf{F}_s^{(r)}\n=\n\\operatorname{diag}\n\\left\\{\ng_i^{(r)}:\ni\\in\\mathcal{I}_s\n\\right\\}.\n$${#eq-common-flips}\n\n\nAs shown in @eq-common-flips, each specification uses the subset of the common study-level sign vector corresponding to the studies it includes. Hence, whenever a study occurs in multiple specifications, the same sign is applied to its score contribution in all of them. If a specification excludes a study, the corresponding element of the common sign vector is simply omitted. This is the construction used by PIMA for specifications involving different subsets of observations [@Girardi2024-ip]. The common sign-flipping transformations preserve the joint resampling dependence among specification-level statistics induced by their shared study-level information.\n\nFor each specification $s$, its constrained null model is fitted and the signed standardized statistic $U_s^{(r)}$ is computed for each common transformation $r=1,\\ldots,B$; for two-sided inference, $T_s^{(r)}=|U_s^{(r)}|$. Inference across the multiverse can then be performed at two levels. First, a global test evaluates $H_{\\mathrm{global}}$. Following PIMA, the flipped statistics can in principle be combined using different non-decreasing functions [@Pesarin2001-xx]. Other combination functions, such as Fisher's or Stouffer's, may offer greater power against diffuse alternatives when interest is restricted to global testing. We use the max-T statistic because it directly supports the subsequent step-down procedure for multiplicity-adjusted inference on individual specifications [@Girardi2024-ip].\n\n$$\nM^{(r)}\n=\n\\max_{s=1,\\ldots,S}\nT_s^{(r)}.\n$${#eq-max-stat}\n\nThe corresponding global $p-value$ is\n\n$$\np_{\\mathrm{global}}\n=\n\\frac{\n\\sum_{r=1}^{B}\n\\mathbb{I}\n\\left(\nM^{(r)}\n\\geq\nM^{(1)}\n\\right)\n}{B}.\n$${#eq-global-p}\n\nRejecting the global null implies that the focal parameter is non-null in at least one specification, thereby providing a global test across the multiverse [@Girardi2024-ip].\n\nThe validity of this construction follows directly from PIMA once the specification-specific `flipmeta` tests satisfy the conditions described in the previous section. For a fixed finite number of specifications, the result requires the joint behavior of the standardized statistics under the common sign-flipping transformations, rather than only the marginal validity of each test. If each specification satisfies the required regularity conditions, the number of independent studies in each specification increases, and the same study-level signs are used across specifications, the resulting PIMMA global test is asymptotically an $\\alpha$-level test [@Girardi2024-ip]. Specifications containing different subsets of studies are accommodated by restricting the common sign vector to the studies included in each specification. Equation @eq-global-p defines a level-$\\alpha$ global test of the global null hypothesis; specification-specific inference requires the step-down adjustment described below.\n\nSecond, post-selection inference can be performed for individual specifications. The implementation used here applies the step-down max-$T$ procedure [@Westfall1992-es; @Westfall2008-py]. Hypotheses are ordered according to the observed evidence, and at each step the reference distribution of the maximum is computed over the hypotheses not yet rejected. Rejected hypotheses are removed before the next step, yielding multiplicity-adjusted $p-values$ with strong control of the FWER under the joint resampling results established for PIMA [@Girardi2024-ip]. The maximum over all $S$ specifications in @eq-max-stat therefore describes the global test and the first step of the procedure, not the complete step-down adjustment.\n\n# Simulation study\n\nWe used simulation to examine the finite-sample Type I error and power of the specification-level `flipmeta` test under selected conditions, including deliberate misspecification of the variance structure. The simulation focuses on this component because the global and step-down procedures of PIMMA inherit their validity from the PIMA framework once the specification-level tests satisfy the required conditions. Standard permutation-based procedures for meta-analysis [@Follmann1999-ha; @Higgins2004-gf] were not included because they require repeated permutation of the model matrix and refitting of the complete meta-analytic model, resulting in a prohibitive computational cost. Moreover, these procedures are formulated for inference within individual models and do not provide the common study-level resampling structure required for multiverse inference.\n\nData were generated following the general simulation framework of @Viechtbauer2015-tn. We considered meta-analyses consisting of $k$ independent studies, each comparing an experimental group ($E$) with a control group ($C$) on a quantitative outcome. For study $i=1,\\ldots,k$, observations in the two groups were assumed to follow normal distributions with means $\\mu_i^E$ and $\\mu_i^C$ and a common within-study standard deviation $\\sigma_i$. The true standardized mean difference for study $i$ was therefore\n\n$$\n\\theta_i\n=\n\\frac{\\mu_i^E-\\mu_i^C}{\\sigma_i}.\n$$\n\nFor each simulated study, we computed the observed standardized mean difference as\n\n$$\nd_i\n=\n\\frac{\\bar{x}_i^E-\\bar{x}_i^C}{s_i},\n$$\n\nwhere $\\bar{x}_i^E$ and $\\bar{x}_i^C$ are the observed group means and $s_i$ is the pooled standard deviation. The approximately unbiased estimator of $\\theta_i$ was then obtained using the small-sample correction [@Hedges1981-za],\n\n$$\ny_i=J(m_i)d_i,\n\\qquad\nJ(m_i)\n=\n\\frac{\n\\Gamma(m_i/2)\n}{\n\\sqrt{m_i/2}\\,\\Gamma\\{(m_i-1)/2\\}\n},\n\\qquad\nm_i=n_i^E+n_i^C-2.\n$${#eq-g}\n\nThis gamma-function ratio is the correction implemented by `metafor::escalc(measure = \"SMD\")`; $J(m_i)\\approx 1-3/(4m_i-1)$ is a commonly used approximation.\n\nUsing the default `vtype = \"LS\"`, the corresponding sampling variance was estimated as\n\n$$\nv_i = \n\\frac{1}{n_i^E}\n+\n\\frac{1}{n_i^C}\n+\n\\frac{y_i^2}\n{2\\left(n_i^E+n_i^C\\right)}.\n$$\n\nThe true study effects were generated from the scalar mixed-effects meta-regression model\n\n$$\n\\theta_i\n=\n\\beta_0+\\beta_X x_i+\\gamma_Z z_i+u_i,\n\\qquad\nu_i\\mid x_i,z_i\\sim\\mathcal{N}(0,\\tau_i^2),\n$$\n\nwhere the location model included one focal moderator $x_i$ and one nuisance moderator $z_i$, together with an intercept. The two moderators were generated from a bivariate normal distribution with zero means, unit variances, and correlation $\\rho_{XZ}\\in\\{0,0.5,0.8\\}$. The intercept was fixed at $\\beta_0=0$, the nuisance coefficient at $\\gamma_Z=0.2$, and the focal coefficient at $\\beta_X\\in\\{0,0.2\\}$. Thus, $\\beta_X=0$ was used to estimate the Type I error rate and $\\beta_X=0.2$ to estimate power.\n\nTo examine robustness to misspecification of the heterogeneity structure, residual random effects were generated from a location--scale meta-regression model [@Viechtbauer2022-rz], with study-specific heterogeneity variance given by the normalized log-linear scale model\n\n$$\n\\tau_i^2\n=\n\\tau_0^2\n\\exp\\left(\n\\zeta x_i - \\frac{\\zeta^2}{2}\n\\right),\n$$\n\nwhere the same focal moderator $x_i \\sim \\mathcal{N}(0,1)$ used in the location model also determined the heterogeneity variance. Because $E\\{\\exp(\\zeta x_i)\\}=\\exp(\\zeta^2/2)$, the term $-\\zeta^2/2$ normalizes the parametrization so that $E(\\tau_i^2)=\\tau_0^2$. The scale coefficient $\\zeta$ was set to $0$, $\\log(1.5)$, or $\\log(2)$, corresponding to no change, a 50% increase, or a 100% increase in $\\tau_i^2$ per standard-deviation increase in $x_i$. We set $\\tau_0^2\\in\\{0,0.05\\}$ and excluded the logically redundant conditions with $\\tau_0^2=0$ and $\\zeta\\ne0$.\n\nAlthough the data were generated with moderator-dependent heterogeneity when $\\zeta>0$, the fitted equal-effects and conventional random-effects meta-regression models did not include a scale component. These conditions therefore assessed the inferential procedures under deliberate misspecification of the heterogeneity structure while retaining a correctly specified location model.\n\nThe number of studies was varied over $k\\in\\{10,30,60,80\\}$. Within each study, the two groups had the same fixed sample size, $n_i^E=n_i^C=n$, with $n\\in\\{15,40,80\\}$. The control-group mean was fixed at zero, the experimental-group mean at the study-specific true effect, and the population standard deviation at one in both groups. Sample means and standard deviations were then generated from their sampling distributions. @tbl-sim-grid summarizes the simulation structure.\n\n| Component                    | Values |\n|------------------------------|--------|\n| Focal moderator              | $n_X = 1$ |\n| Nuisance moderator           | $n_Z = 1$ |\n| Intercept                    | $\\beta_0 = 0$ |\n| Focal coefficient            | $\\beta_X \\in \\{0, 0.2\\}$ |\n| Nuisance coefficient         | $\\gamma_Z = 0.2$ |\n| Moderator correlation        | $\\rho_{XZ} \\in \\{0, 0.5, 0.8\\}$ |\n| Baseline heterogeneity       | $\\tau_0^2 \\in \\{0, 0.05\\}$ |\n| Scale coefficient            | $\\zeta \\in \\{0, \\log(1.5), \\log(2)\\}$ if $\\tau_0^2 = 0.05$; $\\zeta = 0$ if $\\tau_0^2 = 0$ |\n| Number of studies            | $k \\in \\{10, 30, 60, 80\\}$ |\n| Sample size per group        | $n \\in \\{15, 40, 80\\}$ |\n| Fitted meta-regression model | EE or RE-REML |\n| Sign-flipping transformations| $B = 5,000$ per simulated dataset |\n| Monte Carlo replications     | 5,000 per condition |\n: Simulation grid parameter space, generating values, and fitted meta-regression models. {#tbl-sim-grid}\n\nFor each condition, the focal coefficient was tested using Wald, KH, mKH, RVE, and `flipmeta`. The `flipmeta` test used $B = 5{,}000$ sign-flipping transformations for each simulated dataset. All procedures were evaluated at the nominal significance level $\\alpha=0.05$. Performance was quantified by the empirical Type I error rate when $\\beta_X=0$ and by empirical power when $\\beta_X=0.2$.\n\nFor power comparisons, a method was included in a given condition when its empirical Type I error did not exceed the upper bound of the 95% Monte Carlo confidence interval around the nominal level of $\\alpha = .05$.\n\nFigures [-@fig-type1-sim] and [-@fig-power-sim] illustrate rejection rates averaged over sample size per group and moderator correlation, separately for each number of studies, fitted model, baseline heterogeneity, and scale coefficient. Wald was omitted from the Type I error figure because its rejection rates were more extreme than those of the other approaches, consistent with previous simulation studies [@Viechtbauer2015-tn].\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Empirical Type I error rates across inferential methods in the simulation study ($\\alpha = 0.05$). Rejection rates for testing the focal moderator coefficient ($\\beta_X = 0$) are averaged over sample size per group ($n$) and moderator correlation ($\\rho_{XZ}$), shown as a function of the number of studies ($k$), baseline heterogeneity ($\\tau_0^2$), scale heterogeneity parameter ($\\zeta$), and fitted model type (Equal-Effects [EE] vs. Random-Effects REML [RE--REML]). Dotted horizontal lines indicate the 95% Monte Carlo confidence interval around nominal $\\alpha = 0.05$. The Wald test is omitted because it showed inflated Type I error rates across many simulated conditions (median = 0.07, max = 0.18).](pimma_files/figure-pdf/fig-type1-sim-1.pdf){#fig-type1-sim fig-align='center'}\n:::\n:::\n\n\nType I error control differed across inferential procedures. In the displayed averages, `flipmeta` showed rejection rates close to the nominal level, ranging from .040 to .052 across values of $k$, fitted model, baseline heterogeneity, and $\\zeta$. RVE was also generally well calibrated, although it was more conservative when the number of studies was small, with displayed average rejection rates as low as .033, and approached the nominal level as $k$ increased. In contrast, KH became increasingly liberal as $\\zeta$ increased: its average Type I error rose from approximately .048 when $\\zeta = 0$, to .052 when $\\zeta = .41$, and .060 when $\\zeta = .69$, reaching a displayed maximum of .062. mKH showed a different pattern, being markedly conservative under homogeneous conditions, particularly for small $k$ (minimum displayed rejection rate = .012), but becoming progressively less conservative and eventually losing Type I error control as $\\zeta$ increased, with displayed average rejection rates up to .062.\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Empirical power across inferential methods in the simulation study ($\\alpha = 0.05$, $\\beta_X = 0.20$). Power is shown only for method-condition combinations that adequately controlled the Type I error rate under the corresponding null condition. Rejection rates are averaged over sample size per group ($n$) and moderator correlation ($\\rho_{XZ}$), shown as a function of the number of studies ($k$), baseline heterogeneity ($\\tau_0^2$), scale heterogeneity parameter ($\\zeta$), and fitted model type (Equal-Effects [EE] vs. Random-Effects REML [RE--REML]). The Wald test is omitted because of its generally inflated Type I error rates.](pimma_files/figure-pdf/fig-power-sim-1.pdf){#fig-power-sim fig-align='center'}\n:::\n:::\n\n\nPower comparisons were restricted to procedures that adequately controlled the Type I error rate in the corresponding conditions. Within these conditions, `flipmeta` and RVE showed broadly similar power. Rejection rates for procedures exhibiting liberal Type I error should not be interpreted as evidence of superior power.\n\nThe joint sign-flipping scheme becomes particularly useful when moving from a single model to a multiverse analysis. General procedures such as Bonferroni or Holm also control the FWER under arbitrary dependence, but do not exploit the dependence among tests and may consequently lose power when specifications are correlated. Consider two intercept-only specifications based on the same $k$ studies, differing only in whether an equal-effects model (i.e., fixing $\\tau^2 = 0$) or a random-effects model is fitted. The score vectors, and consequently the signed standardized statistics, are likely to be correlated, especially when $\\tau^2$ is close to zero. For testing the intercept $\\beta$ under $H_0:\\beta=0$, there are no nuisance predictors, $\\tilde{x}_i=1$, and $\\hat{r}_{H_0,i}=y_i$. The score contribution therefore simplifies to $\\nu_i=\\hat{w}_{H_0,i}y_i$. Since $y_i$ is identical across these two specifications, differences in the score contributions arise from the study weights. As $\\hat{\\tau}^2$ approaches zero, the random-effects weights approach the equal-effects weights, making the corresponding score vectors increasingly similar. As a practical example, we use the dataset from the meta-analysis by @Crede2010-ej on the relationship of class attendance with grades and student characteristics. The dataset is included in the `metafor` R package [@Viechtbauer2010-xz].\n\n\n::: {.cell layout-align=\"center\"}\n\n```{#lst-ex-multi .r .cell-code  lst-cap=\"Correlations between signed standardized statistics in a multiverse meta-analysis\"}\nlibrary(metafor)\nset.seed(24617)\n\n#library(flipmeta)\n\ndat <- dat.crede2010\n# calculating Fisher z transformed correlation coefficient\ndat <- escalc(\"ZCOR\", ri = ri, ni = ni, data = dat)\ndat$id <- 1:nrow(dat)\n\n# scenario 1, full data, random-effects\nfit1 <- rma(yi, vi, data = dat, method = \"REML\")\n\n# scenario 2, journal articles only\n# (excluding dissertations and other sources), random-effects\nfit2 <- rma(yi, vi, data = dat[dat$source == \"journal\", ])\n\n# scenario 3, full data, equal-effects (tau2 = 0)\nfit3 <- rma(yi, vi, data = dat, method = \"EE\")\n\nfitl <- list(fit1, fit2, fit3)\n\n# multiverse analysis, 1000 sign flips\nres <- flipmeta(fitl, B = 1000, id = \"id\", progress = FALSE)\n\n# extracting the B x 3 matrix of signed standardized statistics\n# and calculating the correlations\n\nR <- cor(res$Tspace)\nround(R, 2)\n\n# raw p values\nres$summary_table$p\n# step-down max-T p values\np.adjust(res)$summary_table$p.adj\n##              mod1:intrcpt mod2:intrcpt mod3:intrcpt\n## mod1:intrcpt         1.00         0.83         0.61\n## mod2:intrcpt         0.83         1.00         0.53\n## mod3:intrcpt         0.61         0.53         1.00\n## [1] 0.001 0.001 0.001\n## [1] 0.001 0.001 0.001\n```\n:::\n\n\n@lst-ex-multi compares three specifications: a full-data RE--REML model, an RE--REML model restricted to journal articles, and a full-data EE model. Their signed standardized statistics are positively correlated, although the specifications differ in both included studies and fitted model. The example therefore illustrates the dependence among tests and how the joint sign-flipping distribution supports step-down max-$T$ adjustment. As a simple illustration of the broader role of dependence, @Li2005-ck proposed estimating the effective number of independent tests from the correlation structure. Under compound symmetry, for example, 100 tests with a common correlation of $\\rho = 0.5$ correspond to approximately 51 effective tests according to their method. Adjusting for all 100 hypotheses without exploiting their dependence can therefore be unnecessarily conservative. PIMMA addresses this problem directly by incorporating the joint dependence structure of the test statistics.\n\n# Application to psychotherapy for depression\n\n## Dataset and original investigation\n\nWe illustrate PIMMA using the database assembled for the multiverse meta-analysis of psychological treatments for depression. The study was first described in a preregistered protocol by @Plessen2022-ju and was subsequently completed and reported by @Plessen2023-ex. Its purpose was to assess whether conclusions about the efficacy of psychotherapy for depression were robust across the many defensible decisions available to meta-analysts.\n\nThe authors searched PubMed, Embase, PsycINFO, and the Cochrane Central Register of Controlled Trials for randomized controlled trials published up to January 1, 2022. Studies comparing a psychological treatment with a control condition were eligible without restrictions on psychotherapy type, target population, treatment format, control condition, or definition of depression. The resulting database comprised 1,206 effect-size estimates from 415 studies and 71,454 participants.\n\nIn the original investigation, combinations of inclusion criteria and statistical methods produced 4,281 meta-analyses. The results generally supported the efficacy of psychotherapy, while also showing that effect estimates varied systematically with choices such as control condition, risk-of-bias restrictions, and adjustment for publication bias [@Plessen2023-ex].\n\nThe present application is not intended to reproduce the full multiverse or provide a definitive assessment of psychotherapy for depression. Instead, we use a clinically more homogeneous subset of the database to illustrate post-selection inference across closely related meta-analytic specifications. We restricted the analysis to studies of CBT in adult populations.\n\nBefore applying the specification-specific eligibility criteria, this subset contained 275 effect-size estimates from 86 independent studies. Studies contributed a median of 2 effect-size estimates (range: 1--20). Individual multiverse specifications then applied different restrictions on control condition, risk of bias, treatment format, and outcome rater [@tbl-application-grid]. As a result, the number of eligible effect sizes and studies varied across specifications. After applying these criteria and aggregating dependent effect sizes within study, each meta-analytic specification included between 6 and 86 independent studies.\n\n## Data preparation\n\nThe available standardized mean differences were expressed as Hedges' $g$, with positive values indicating effects favoring CBT. Their sampling variances were obtained from the corresponding standard errors. Records without an available effect-size estimate were excluded. Study identifiers and the variables used to define the multiverse---including treatment and control conditions, treatment format, target population, outcome rater, and risk of bias---were harmonized before applying the eligibility criteria.\n\nBecause individual studies could contribute multiple effect sizes, eligibility criteria were first applied separately within each specification. The included effect sizes were then aggregated within study using `metafor::aggregate.escalc()`, so that each study contributed a single effect-size estimate and sampling variance to the corresponding meta-analysis. Within studies, sampling errors were assumed to follow a compound-symmetric correlation structure with a common pairwise correlation $\\rho$. Effect sizes were combined using inverse-variance weighted generalized least squares. Because these within-study correlations were not available, we treated $\\rho$ as an additional multiverse decision and considered $\\rho \\in \\{.30, .50, .70\\}$. This aggregation was necessary because the current PIMMA formulation assumes independent study-level contributions.\n\nAfter aggregation, each specification therefore contained one effect-size estimate per study. The study, rather than the individual outcome, was the independent unit entering the meta-analysis and contributing to the study-level scores used by PIMMA. Importantly, aggregation was performed after applying the specification-specific eligibility criteria, because different specifications could retain different effect sizes from the same study.\n\n## Multiverse specifications\n\nAll specifications estimated an intercept-only random-effects model, with pooled Hedges' $g$ as the parameter of interest. Following @Del-Giudice2021-aq, we included analytical choices for which the alternative options could be considered approximately equally reasonable and defensible, rather than mechanically including every technically possible analysis. The resulting multiverse therefore necessarily reflects researcher judgment. This is appropriate here because the application is intended to illustrate PIMMA rather than provide a definitive assessment of the efficacy of CBT for depression.\n\nWithin this set of defensible alternatives, the multiverse varied four decisions about which evidence was included in each meta-analysis and two decisions about within- and between-study variance (@tbl-application-grid). For each evidence-selection decision, the unrestricted option imposed no restriction on that characteristic and included all otherwise eligible categories. Crossing these decisions produced $3 \\times 3 \\times 4 \\times 3 \\times 3 \\times 2 = 648$ candidate specifications. To avoid meta-analyses based on extremely sparse subsets, we required each specification to include at least six independent studies, leaving 438 eligible decision paths. We then removed paths producing exactly the same final meta-analytic model, leaving 336 unique analyses. The mapping from the eligible decision paths to the unique analyses was retained. When multiple values of an analytical decision produced the same final model, that decision is labeled non-discriminating rather than being assigned the label of the first path encountered.\n\nAs a conventional inferential benchmark, we compared PIMMA, combining specification-level `flipmeta` tests with step-down max-$T$ adjustment, with RVE followed by Holm correction. RVE showed similar specification-level Type I error control and power to `flipmeta` in the simulation study, while Holm controls the FWER without requiring an estimate of the dependence among tests. This comparison concerns two complete inferential pipelines and therefore reflects differences in both specification-level inference and multiplicity adjustment.\n\nPIMMA inference was based on $B = 5,000$ common sign-flipping transformations. The same number of transformations was used in the sensitivity analysis excluding specifications with fewer than 10 studies.\n\n| Specification decision | Levels |\n|------------------------------------|------------------------------------|\n| Control condition | Waitlist; care as usual; unrestricted |\n| Risk of bias | Low risk only; low risk or some concerns; unrestricted |\n| Treatment format | Individual; group; guided self-help; unrestricted |\n| Outcome rater | Clinician-rated; self-reported; unrestricted |\n| Within-study correlation | $\\rho = .30$, $.50$, or $.70$ |\n| Heterogeneity estimator | Restricted maximum likelihood; DerSimonian--Laird |\n\n: Analytical decisions and corresponding levels defining the multiverse of specifications for the CBT depression application. {#tbl-application-grid}\n\n\n## Results\n\n\n\n::: {.cell layout-align=\"center\"}\n\n:::\n\n\n\n\n\n\n::: {.cell layout-align=\"center\"}\n::: {.cell-output-display}\n![Overview of the CBT depression multiverse ($S = 336$). The left panel shows the relationship between pooled effect-size estimates (Hedges' $g$) and adjusted $-\\log_{10}(p)$ values from step-down max-$T$ correction. Points distinguish analyses that were not significant, significant only before multiplicity adjustment, or significant after step-down max-$T$ adjustment; the horizontal dotted line marks the $\\alpha = 0.05$ threshold. The upper-right panel shows the distribution of pairwise correlations among specification-level signed standardized statistics, with the dashed vertical line marking the median. The lower-right panel shows the distribution of the number of studies included in each analysis.](pimma_files/figure-pdf/fig-application-overview-1.pdf){#fig-application-overview fig-align='center'}\n:::\n:::\n\n\nThe 336 included specifications differed substantially in the amount of evidence included, ranging from 6 to 86 independent studies (median = 13.5, Q1-Q3 = 9--27). Pooled Hedges' $g$ estimates also varied, ranging from 0.36 to 1.30, with a median of 0.72 (Q1-Q3 = 0.59--0.96). Despite this variability, all pooled effect estimates were positive.\n\nThe global PIMMA test rejected the global null hypothesis that the average effect was zero in all 336 specifications ($p$ = .00020). This provides evidence that the average effect differs from zero in at least one specification, but it does not tell us which individual specifications remain statistically significant after correcting for multiple testing.\n\nAt the specification level, 330 of the 336 specifications (98.2%) had an unadjusted `flipmeta` $p$-value $\\leq .05$. After step-down max-$T$ adjustment accounting for dependence among specifications, 297 specifications (88.4%) remained significant (@tbl-inference-comparison; @fig-application-overview). As a conventional benchmark, RVE with Holm adjustment yielded 233 specifications (69.3%). This comparison evaluates the complete PIMMA and RVE--Holm pipelines; it does not isolate the contribution of the marginal test from that of the multiplicity adjustment.\n\nThe proportion of significant specifications should be interpreted as a descriptive summary of this particular multiverse, not as an estimate of the probability that the effect is present.\n\nThe dependence among specification-level signed standardized statistics varied considerably (@fig-application-overview). Pairwise correlations had a median of 0.20 (Q1-Q3 = 0.02--0.45), ranging from -0.04 to 1.00. This is expected because some specifications retain substantially different sets of studies, whereas others share the same or very similar evidence and differ only in a small number of analytical choices. The step-down max-$T$ procedure uses this dependence structure, whereas Holm controls the FWER without explicitly using it.\n\nThe sensitivity analysis excluding specifications with fewer than 10 independent studies included 246 specifications. The global null was again rejected ($p$ = .00020), and 246 specifications remained significant after step-down max-$T$ adjustment. RVE with Holm adjustment retained 216 specifications (87.8%).\n\n\n\n\n::: {#tbl-inference-comparison .cell layout-align=\"center\" tbl-cap='Specification-level inferential results across the CBT depression multiverse ($S = 336$), comparing unadjusted and multiplicity-adjusted inference using flipmeta and RVE.'}\n::: {.cell-output-display}\n\n\n|Method                     | Significant specifications | Percentage (%) |\n|:--------------------------|:--------------------------:|:--------------:|\n|flipmeta (unadjusted)      |            330             |      98.2      |\n|flipmeta + step-down max-T |            297             |      88.4      |\n|RVE (unadjusted)           |            313             |      93.2      |\n|RVE + Holm                 |            233             |      69.3      |\n\n\n:::\n:::\n\n\n# Discussion\n\nPIMMA addresses two related inferential problems. First, `flipmeta` provides inference within each individual meta-analytic specification. Second, PIMMA extends this inference across the whole multiverse, providing both a global test and adjusted inference for individual specifications. Both levels are needed because valid inference within single meta-analyses does not by itself account for the additional selection problem created by examining many specifications.\n\nCrucially, PIMMA allows researchers to inspect the multiverse and then focus on specifications of interest while controlling the FWER, as long as the set of admissible specifications was defined independently of the observed results. PIMMA does not identify a single best model or make a poorly justified specification defensible. Instead, it allows specification-level conclusions to be interpreted while accounting for multiplicity across the full multiverse.\n\nThe application illustrates that PIMMA answers two different questions: whether there is evidence of an effect somewhere in the multiverse, and which individual specifications remain statistically significant after correcting for multiple testing. The second question is often more informative, because rejecting the global null only shows that the effect differs from zero in at least one specification, without determining which individual specifications remain statistically significant after multiplicity adjustment.\n\nIn the CBT example, all pooled estimates were positive, although their magnitude varied considerably across specifications. The global null was rejected, and most specifications remained significant after step-down max-$T$ correction. The application also shows why accounting for dependence is important. Specifications often share studies and analytical choices, so their test statistics are correlated, and PIMMA incorporates this dependence in the multiplicity adjustment. Compared with the conventional RVE--Holm pipeline, which retained 233 significant specifications, PIMMA retained 297. Because the two pipelines differ in both specification-level inference and multiplicity adjustment, this comparison should be interpreted as an overall benchmark rather than as an isolated assessment of the adjustment procedures. In the sensitivity analysis excluding specifications with fewer than 10 studies, 246 of the 246 included specifications remained significant after step-down max-$T$ correction, suggesting that the main conclusion was not driven by the smallest meta-analytic subsets.\n\nThese findings should therefore be interpreted mainly as a demonstration of the PIMMA framework, rather than as a definitive reassessment of the clinical efficacy of CBT for depression.\n\n\n# Limitations and future perspectives\n\nThe current implementation relies on independent study-level contributions to the score. When studies contribute multiple dependent effect sizes, these contributions can be reduced to the study level, as in the present application, or handled through extensions of the sign-flipping framework developed for some hierarchical structures [@Andreella2025-nd; @Vesely2026-zj]. However, reliable inference still requires a sufficient number of independent studies, which may be a limitation for specifications based on only a few studies. More complex dependence structures, including crossed structures for which current resampling schemes do not guarantee valid inference, remain an important direction for future work.\n\nPIMMA provides inference conditional on the set of specifications included in the multiverse, but it does not determine which analytical choices should be considered reasonable. This limitation is not unique to PIMMA. Methodological knowledge is still required to define a defensible multiverse, while PIMMA provides an inferential framework once that multiverse has been specified. The method therefore complements, rather than replaces, transparent justification of the analytical choices considered. In our application, we deliberately included a limited set of reasonable alternatives because the aim was to illustrate the method rather than provide an exhaustive clinical assessment of CBT.\n\nFinally, the theoretical justification for the specification-level `flipmeta` tests is asymptotic and relies on the conditions described above, including independent study-level contributions. Our simulation study therefore examined how the tests behave with finite numbers of studies, focusing on Type I error control and power under the scenarios considered. Further work is needed to evaluate performance with very few studies, highly uneven study contributions, more complex forms of misspecification, and dependent effect-size structures. The global and step-down PIMMA procedures were not evaluated separately in the simulation study; their theoretical justification follows from the PIMA framework under the conditions described above.\n\n# Conclusion\n\nWithin each meta-analytic specification, `flipmeta` uses study-level sign flipping to test the focal effect, with asymptotic robustness to some forms of variance-structure misspecification under the conditions described above. Across specifications, the same sign flips are applied jointly, preserving the dependence between analyses that share studies. This allows PIMMA to provide both a global test of the multiverse and step-down max-$T$ adjusted $p-values$ with strong FWER control. The simulation study examined how well the specification-level test performs in realistically sized meta-analyses, while the CBT application illustrated how the complete procedure can be used in practice.\n\nMore broadly, PIMMA extends multiverse meta-analysis beyond descriptive robustness assessment and global testing. Given a fixed and defensible set of specifications, researchers can examine the full multiverse and determine which individual results remain statistically significant after accounting for multiple testing and dependence among specifications. PIMMA does not identify a single best model or replace researcher judgment. Rather, it allows researchers to make specification-level inferences while accounting for the fact that conclusions are drawn after considering multiple reasonable analyses.\n\n\n# Reproducibility and data availability\n\nAll code required to reproduce the simulations, empirical application, figures, and tables is available in the accompanying repository. The CBT dataset derives from @Plessen2023-ex; access and redistribution follow the conditions of the original data source. Software and package versions used for the analyses are reported in the supplementary materials on the online Github repository [github.com/filippogambarota/pimma](https://github.com/filippogambarota/pimma).\n\n# AI usage\n\nDuring the preparation of this work, the authors utilized ChatGPT (5.6 Sol) to assist with writing and coding.\n\n# References\n\n::: {#refs}\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": null,
    "postProcess": false
  }
}